config/routes.rb
Rails.application.routes.draw do

  get  'couch_types/index'
  get 'couches/index'
  resources :puntuacions
  resources :couches
  resources :configurations do
    get :seleccionfechas, on: :collection
    get :usuariosregistrados, on: :collection
  end
  resources :couch_types

  resources :reservas do
    get :aceptar, on: :member
    get :rechazar, on: :member
    get :cancelar, on: :member
    get :visto, on: :member
  end 
  resources :premiums
  resources :consultas

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions", :passwords => "passwords"}
  root 'couches#index'
  devise_scope :user do
    get '/users/show', to: 'registrations#show'
    get '/solicitudes', to:'registrations#missolicitudes'
    get '/misreservas', to: 'registrations#misreservas'
  end
  get '/couchinn', to: 'main#index'
  resources :premiums
  get '/puntuacion/recibidas', to: 'puntuacions#recibidas'
  get '/couch/reservas', to:'couches#indexreservas'
  get '/couch/estadias', to:'couches#indexestadias'

 
  

end

app/models/couch.rb
class Couch < ActiveRecord::Base
belongs_to :user
belongs_to :couch_type
has_many :puntuacions
has_many :reservas
has_many :consultas
scope :prueba, -> { order ("puntuacion")}
scope :prioridades, -> { order ('"couches"."esPremium" desc') }

def is_free?(check_in, check_out)
    reservas_couch = self.reservas# reservas del couch (por el has_many)
    reservas_confirmadas = reservas_couch.where(confirmada:true) # solo miramos las confirmadas
    #if check_in != nil && check_in != ""
    	reservas_confirmadas = reservas_confirmadas.where('? < fin', check_in) # from se copiaría en el lugar de '?'
    #end
    #if check_out != nil && check_out != ""
    	reservas_confirmadas = reservas_confirmadas.where('? > inicio', check_out) # to se copiaría en el lugar de '?'
    #end
    # Retorno true o false si el resultado de lo anterior 
    # está vacío o no
    return reservas_confirmadas.empty?  
end
def self.filtrados(tipo, lugar, capacidad, puntuacion)

	couches = Couch.all.prioridades

	if lugar != nil 
		couches = couches.where("lugar ILIKE ?", "%#{lugar}%")
	end
	if capacidad != nil && capacidad != "" 
		couches = couches.where( "capacidad >= ?", "#{capacidad}")
	end
	if puntuacion != nil && puntuacion != ""
		couches = couches.where( "puntuacion >= ?", "#{puntuacion}")
	end
	if tipo != nil && tipo != ""
		couches = couches.where( "couch_type_id = ?", "#{tipo}")
	end

	return couches

end
def self.free_couches(tipo, lugar, capacidad, puntuacion, check_in, check_out)
    result = [] # En result agregaremos los hospedajes libres
    c = Couch.filtrados(tipo, lugar, capacidad, puntuacion) 
    c.each do |couch|
      result << couch if couch.is_free?(check_in, check_out) # Agregamos el hospedaje si está libre
    end

    return result
end
def serPremium
	self.esPremium = true
	self.save
end


end

app/models/couch_type.rb
class CouchType < ActiveRecord::Base
	
	validates_uniqueness_of :nombre, :message => "El tipo de Couch ya existe"
	validates_presence_of :nombre, :message => "Este campo no puede estar vacío"

	has_many :couches
	##vaidates_length_of:nombre,minimum:2, message:"El nombre es muy corto"
	##vaidates_length_of:nombre,maximum:30, message: "El nombre es muy largo"
end

app/controllers/couches_controller.rb
class CouchesController < ApplicationController

def show
	id = params[:id]
	if(URI(request.referer).path == '/consultas')
		consultas = Consulta.all
		consultasCouch = consultas.where(couch_id: params[:id])
		consultasUser = consultasCouch.where(user_id: current_user)
		consultasUser.each do |c|
			c.vista
		end
	end
	total=0
	@couch = Couch.find(params[:id])
	Puntuacion.where('couch_id = ?', id).each do |p|
		total = p.valor + total

	end

	if Puntuacion.where('couch_id = ?', id).count == 0
		@couch.puntuacion = 0
	else
	@couch.puntuacion = total / Puntuacion.where('couch_id = ?', id).count
	end
end	

def edit
	@couch = Couch.find(params[:id])
end

def update
	@couch = Couch.find(params[:id])
	@couch.update(params.require(:couch).permit(:nombre, :descripcion, :lugar, :capacidad, :imagen, :couch_type_id))
	redirect_to couches_path
end


def index		
	tipo = params[:couch_type_id]
	lugar = params[:lugar]
	capacidad = params[:capacidad]
	puntuacion = params[:puntuacion]
	check_in = params[:ida]
	check_out = params[:vuelta]

	@couches = Couch.free_couches(tipo, lugar, capacidad, puntuacion, check_in, check_out)
end


def indexreservas
	@couch = Couch.find(params[:couch_id])
end

def indexestadias
	reservas_confirmadas = Reserva.all.where(confirmada:true)
	reservas_concluidas = reservas_confirmadas.where('? > fin', Date.today)
	mis_reservas = reservas_concluidas.where('user_id = ?', current_user.id)
	resultado = []
	Couch.all.each do |c|
		if !mis_reservas.where('couch_id = ?', c.id).empty?
			resultado << c
		end
	end
	@couches = resultado
end

#	@couches = Couch.all.prioridades

#	if lugar != nil 
#		@couches = @couches.where("lugar ILIKE ?", "%#{lugar}%")
#	end
#	if capacidad != nil && capacidad != "" 
#		@couches = @couches.where( "capacidad >= ?", "#{capacidad}")
#	end
#	if puntuacion != nil && puntuacion != ""
#		@couches = @couches.where( "puntuacion >= ?", "#{puntuacion}")
#	end
#	if tipo != nil && tipo != ""
#		@couches = @couches.where( "couch_type_id = ?", "#{tipo}")
#	end
#	if (ida) && (vuelta)
#		@couches = @couches.where("")
#	end


#	Client.where("created_at >= :start_date AND created_at <= :end_date",
 # {start_date: params[:start_date], end_date: params[:end_date]}

#if (params[:lugar])
#	@couches = Couch.all.where( :lugar => params[:lugar])
#end
#if (!params[:lugar])
#	@couches = Couch.all 
#else
#	@couches = Couch.all
#end

def new
	@couch = Couch.new
end 

def create
	@couch = Couch.new(params.require(:couch).permit(:nombre, :couch_type_id, :descripcion, :lugar, :capacidad, :imagen))
	@couch.user = current_user

	if @couch.save
		redirect_to couches_path
	else
		redirect_to new_couch_path, notice: "Hay campos vacios"
	end

end

def destroy
	couch = Couch.find(params[:id])
	couch.destroy
	redirect_to users_show_path
end
end

app/helpers/couches_helper.rb
module CouchesHelper
end

app/views/couches/_form.html.erb
<%= form_for @couch do |f| %>
	<div class="row">	
  	<div class="col-md-3 col-md-offset-4" >
      <%= f.label :nombre, 'Nombre'%>
  		<%= f.text_field :nombre, required: true, class: 'form-control', placeholder: 'Ingrese el nombre del Couch'  %>
  		<%= f.label :descripcion, 'Descripcion'%>
  		<%= f.text_field :descripcion, required: true, class: 'form-control', placeholder: 'Ingrese descripcion del Couch'  %>
  		<%= f.label :lugar, 'Lugar'%>
  		<%= f.text_field :lugar, required: true, class: 'form-control', placeholder: 'Ingrese lugar del Couch'  %>
  		<%= f.label :capacidad, 'Capacidad'%>
  		<%= f.number_field :capacidad, required: true, class: 'form-control', min: 1, max: 100 %>
  		<%= f.label :imagen, 'URL de la imagen'%>
  		<%= f.text_field :imagen, required: true, class: 'form-control', placeholder: 'Ingrese el URL'  %>
  		<%= f.label :couch_type_id, "Tipo de Couch" %><br />
      <%= f.select :couch_type_id, CouchType.all.where(activo:true).collect { |c| [ c.nombre, c.id]} %>
  	</div>
  </div>
	<br>
	<div class="row">
		<div class="col-md-3 col-md-offset-4">
			<%= f.submit "Aceptar", class: 'btn btn-success' %>
			<%= link_to "Cancelar", :back, class: 'btn btn-success' %>
		</div>
	</div>
<% end %>	

app/views/couches/edit.html.erb
<div class="container">
	<h1 style="color:#6B8E23;" class="text-center"> Editar Couch </h1>
	<br>
	<%= render 'form' %>
</div>

app/views/couches/index.html.erb
<body class="bgcolor">

<% if user_signed_in? %>

<% novistas=0 %>
<% current_user.couches.each do |couch| %>
  <% novistas = novistas + couch.reservas.novistas.count %>
<% end %>
<% novistas = novistas + current_user.reservas.novistas.count %>

<% if novistas != 0 %>
<div class="container bggreen">
  <h2 style="color:white"> Se actualizaron tus reservas! </h2>
  
  <!-- reservas sobre mis couches -->
  <% current_user.couches.each do |couch| %>
    <% if  couch.reservas.novistas.count != 0 %>
      <% couch.reservas.novistas.each do |reserva| %>
         <h4 style="color:white"> La reserva sobre el couch <%= reserva.couch.nombre %> fue cancelada por <%= reserva.user.nombre %> <%= reserva.user.apellido %>
        <%= link_to 'Aceptar', visto_reserva_path(reserva), class: "btn btn-default btn-xs" %></h4>
      <% end %>
    <% end %>
  <% end %>

  <!-- solicitudes -->
  <% if current_user.reservas.novistas.count != 0 %>
    <%  current_user.reservas.novistas.each do |reserva| %>
      <% if reserva.cancelada %>
        <h4 style="color:white"> La reserva sobre el couch <%= reserva.couch.nombre %> fue cancelada por su dueño
        <%= link_to 'Aceptar', visto_reserva_path(reserva), class: "btn btn-default btn-xs" %></h4>
      <% else %>
        <% if reserva.rechazada %>
          <h4 style="color:white"> La reserva sobre el couch <%= reserva.couch.nombre %> fue rechazada 
          <%= link_to 'Aceptar', visto_reserva_path(reserva), class: "btn btn-default btn-xs" %></h4>
        <% else %>
          <h4 style="color:white"> La reserva sobre el couch <%= reserva.couch.nombre %> fue confirmada
          <%= link_to 'Aceptar', visto_reserva_path(reserva), class: "btn btn-default btn-xs" %></h4>
          
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>  
<% end %>

<% end %>


</br>
<div class="container"> 
  <div class="row"> 
    <div class="jumbotron">
      <h2 style="color:white"> Búsqueda </h2>    
      <%= form_tag couches_path , method: :get do %>

      <div class="col-md-3">

        <div style:"color:white">
          <%= label_tag :lugar %>
        </div>
        <%= text_field_tag :lugar %>
       
        <div style:"color:white" >
        <br />
          <%= label_tag :capacidad %>
        </div>
        <%= number_field_tag :capacidad, nil, within: 1...101 %>

        <p></p>
        <%= submit_tag("Buscar") %>

       
      </div>

      <div class="col-md-3">

        <div style:"color:white" >
          <%= label_tag :puntuacion %>
        </div>
        <%= number_field_tag :puntuacion, nil, within: 1...6 %>   

        <div style:"color:white" >
        <br />
          <%= label_tag :tipo %>
        </div>
        <%= select_tag( :couch_type_id, options_for_select(CouchType.all.collect { |c| [ c.nombre, c.id]}), {include_blank: 'Todos'}) %>

      </div>

      <div class="col-md-3">

        <div style:"color:white" >
          <%= label_tag :fecha_ida  %>
        </div>
        <%= text_field_tag :ida, Date.today, type: :date %>

        
        <div style:"color:white" >
        <br />
          <%= label_tag :fecha_vuelta  %>
        </div>
        <%= text_field_tag :vuelta, Date.today, type: :date %>
  
      </div>
   

     
      <%end%>
    </div>
  </div>
</div>

<h1 style="color:#6B8E23;" class="text-center"> <strong>Lista de Couches</strong></h1>
<p></p>
  <div class="row">
    <div class="col-md-6 col-md-offset-1">
      <ul class="media-list">
      <li class="media">
      <% if @couches == nil %>
        <p class="alert tipoRegistroCentro" style="color:red"><strong>No se han encontrado coincidencias</p>  
      <% else %>
      <% @couches.each do |couch| %>

        <div class="media"> 
          <div class="pull-left">
            <img class="img-rounded" class="media-object" src= <%= couch.imagen %>  alt="imagen" style="width:200px;height:150px" >
          </div>
          <div class="media-body">
            <h4 class="media-heading"><%= couch.nombre %> <small><i> <%= couch.lugar %></i></small></h4>
            <p> <%= couch.descripcion %> </p>
            <p> Capacidad: <%= couch.capacidad %></p>
            <% 
            total=0 
            Puntuacion.where('couch_id = ?', couch.id).each do |p|
                total = p.valor + total
            end
            if Puntuacion.where('couch_id = ?', couch.id).count == 0
                 couch.puntuacion = 0
            else
                couch.puntuacion = total / Puntuacion.where('couch_id = ?', couch.id).count
            end%>     
            <p> Puntuacion: <%= couch.puntuacion %></p> 

             <button class="btn btn-success btn-xs" type="button">
                <%= link_to 'Ver más', couch_path(couch.id), class: "btn btn-success btn-xs" %>
            </button>
              
          </div>
        </div>
      <% end %>
      <% end %>
      </li>
      </ul>
    </div>
    <% if !user_signed_in? || (current_user.esPremium == false) %>
   
      <div class="col-md-3 col-md-offset-1" >
        <container>
          <div class="jumbotron">

            <h2 class="tipoRegistroCentro">Conviertase en un usuario Premium ya!</h2>

            <p class="tipoRegistroCentro"> Disfrute de los grandes beneficios de tener una cuenta Premium!!!</p>
            <p class="tipoRegistroCentro"> Por un precio único tiene la posibildad de que sus couchs tengan prioridad ante la búsqueda.</p>
            <p class="tipoRegistroCentro"> Recuerde que el pago se realiza una sola vez y.. SOS PREMIUM POR SIEMPRE!!!!!!</p>
        
            
          </div>
        </container>

      </div>
    <% end %>

    </div>
  </div>
</body>

app/views/couches/new.html.erb
<div class="container">
	<h1 style="color:#6B8E23;" class="text-center"> Crear un nuevo Couch </h1>
	<br>
	
	<%= render 'form' %>
   </div>
</div>

app/views/couches/show.html.erb
<body>
<center>
  <% if notice %>
  <div class="alert alert-success tipoRegistroCentro" role="alert">
  <strong><%= notice %></strong>
  </div>
  <% end %>
    <h1 style="color:#6B8E23;" class="text-center"> 
    <strong><%= @couch.nombre %> </strong></h1>
    <h4> <i> <%= @couch.lugar %></i></small></h4>  
 
  <div class="row">
  <div class="col-md-6">
  <img src= <%= @couch.imagen %> class="img-rounded" alt="imagen" style="width:300px;height:250px" >
  <p></p>
   <!-- <p></p>
    <p>
    <button class="btn btn-default btn-sm" type="button">
      <%= link_to 'Atrás', couches_path, class: "btn-default" %>
       </button>
    <button class="btn btn-default btn-sm" type="button">
    <%= link_to 'Enviar solicitud', couches_path, class: "btn-default" %>
     </button>
  </p> 
-->
  </div>
  <div class="col-md-6">
   <p></p>
    <p class="text-left"> <strong>Descripción:</strong> <%= @couch.descripcion %> </p>
    <p class="text-left" > <strong>Capacidad:</strong> <%= @couch.capacidad %></p>
    <p class="text-left" > <strong>Puntuacion: </strong> <%= @couch.puntuacion %> </p>
    <p class="text-left" > <strong>Tipo de Couch: </strong> <%= @couch.couch_type.nombre %> </p>
    <p class="text-left"> <strong>Propietario:</strong> <%= @couch.user.nombre %> <%= @couch.user.apellido%> </p>

    <p class="text-left" > <%= image_tag "contacto.png"%>  <strong>Contacto: </strong><%= @couch.user.email %></p>
    <p class = "text-left">
      <button class="btn btn-default btn-sm" type="button">
        <%= link_to 'Atrás', :back, class: "btn-default" %>
      </button>  
      <% if ((user_signed_in?) && (current_user != @couch.user)) then %>
      <!-- Se debe analizar si el usuario es el propietario del couch!!!!!!!!!!!!!!!! -->
        <button class="btn btn-default btn-sm" type="button">
          <%= link_to 'Reservar', new_reserva_path(:couch_id => @couch.id), class: "btn-default" %>
        </button>
      <% end %>
    </p>
    

  </div>
  </div>
  </br>
  </br>
  </br>
  <div class="row">
    <div class="col-md-6 col-md-offset-3"> 
      <h3 class="media-heading" style="color:#6B8E23;"><strong> Consultas </strong></h3>
      <em class="text-left"><small> Las consultas publicadas serán respondidas por el propietario del couch a la brevedad. Aquel usuario que incluya en sus mensajes algún comentario violatorio del reglamento será eliminado e inhabilitado para volver a comentar. Enviar un comentario implica la aceptación del Reglamento.</small></em>
      </br>
      </br>
      </br>
      <% @couch.consultas.each do |consulta| %>
        <ul class="media-list">
        <li class="media">
        <div class="media"> 
          <div class="pull-left">
            <img src= <%= consulta.user.foto %> class = "img-circle" alt="imagen" style="width:50px;height:50px">
            <p> <%= consulta.user.nombreUsuario %></p> 
          </div>
          
          <div class="media-body">
            </br>
            <p class="text-left"> <%= consulta.pregunta %> <small><em><%= consulta.fechaPregunta.day %>/<%= consulta.fechaPregunta.month %>/<%= consulta.fechaPregunta.year %> <%= consulta.fechaPregunta.strftime("%I:%M%p") %></em></small></p>
          </div>

          <% if (consulta.respuesta != nil) %>
            <div class="media"> 
              </br>
              <div class="pull-left">
                <img src= <%= @couch.user.foto %> class = "img-circle" alt="imagen" style="width:50px;height:50px">
                <p> <%= @couch.user.nombreUsuario %> </p> 
              </div>
              <div class="media-body">
              </br>
                <p class="text-left"> <%= consulta.respuesta %> <small><em><%= consulta.fechaRespuesta.day %>/<%= consulta.fechaRespuesta.month %>/<%= consulta.fechaRespuesta.year %> <%= consulta.fechaRespuesta.strftime("%I:%M%p") %></em></small></p>
              </div>
            </div>
          <% else %>
            <% if(current_user == @couch.user) %>
              <button class="btn btn-default btn-sm pull-left" type="button">
                <%= link_to 'Responder', edit_consulta_path(consulta.id), class: "btn-default" %>
              </button>
            <% end %>
          <% end %>
        </div>
        </li>
        </ul>
      <% end %>
      <% if((user_signed_in?)&&(current_user != @couch.user)) %>
        <button class="btn btn-default btn-sm pull-left" type="button">
            <%= link_to 'Consultar', new_consulta_path(:couch_id => @couch.id, :user_id => current_user.id), class: "btn-default" %>
        </button>
      <% end %>
    </div>
  </div>
</center>
</body>