config/routes.rb
Rails.application.routes.draw do

  get  'couch_types/index'
  get 'couches/index'
  resources :puntuacions
  resources :couches
  resources :configurations do
    get :seleccionfechas, on: :collection
    get :usuariosregistrados, on: :collection
  end
  resources :couch_types

  resources :reservas do
    get :aceptar, on: :member
    get :rechazar, on: :member
    get :cancelar, on: :member
    get :visto, on: :member
  end 
  resources :premiums
  resources :consultas

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions", :passwords => "passwords"}
  root 'couches#index'
  devise_scope :user do
    get '/users/show', to: 'registrations#show'
    get '/solicitudes', to:'registrations#missolicitudes'
    get '/misreservas', to: 'registrations#misreservas'
  end
  get '/couchinn', to: 'main#index'
  resources :premiums
  get '/puntuacion/recibidas', to: 'puntuacions#recibidas'
  get '/couch/reservas', to:'couches#indexreservas'
  get '/couch/estadias', to:'couches#indexestadias'

 
  

end

app/controllers/configurations_controller.rb
class ConfigurationsController < ApplicationController
def show
end
def index
end
def registrados
	@users = User.all
end

def seleccionfechas
	
end

def usuariosregistrados
	@premium = false
	@inicio = Date.civil(params[:aux1]["comienzo(1i)"].to_i, params[:aux1]["comienzo(2i)"].to_i, params[:aux1]["comienzo(3i)"].to_i)
	@fin = Date.civil(params[:aux2]["fin(1i)"].to_i, params[:aux2]["fin(2i)"].to_i, params[:aux2]["fin(3i)"].to_i)
	if params[:commit] == "Ver dinero recaudado"
		@premium = true
	end	
end

end

app/helpers/configurations_helper.rb
module ConfigurationsHelper
end

app/views/configurations/index.html.erb
<center>
	<div class="container">
	<h1 style="color:#6B8E23;" class="text-center">Configuración<h1>
	
		<%= link_to "Listado de tipos de Couch", couch_types_path, class: 'btn btn-default' %>
		<br>
		<%= link_to "Agregar un tipo de Couch", new_couch_type_path, class: 'btn btn-default' %>
		<br>
		<%= link_to "Ver usuarios entre dos fechas", seleccionfechas_configurations_path, class: 'btn btn-default' %>
	</div>
</center>



app/views/configurations/registrados.html.erb
<body>
<h1>hola</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table class = "table center">
      <tr>
        <th> <h1 style="color:#6B8E23;" class="text-center"> <strong>Lista de usuarios registrados </strong></h1> </th>
        <th> Activo </th>
        <th></th>
      </tr>
      <% @users.each do |user| %>
          <tr> 
            <td> <%= user.nombre %> </td>
            <td> <%= user.apellido %></td>
            <td> <%= user.created_at %></td>
          </tr>
      <% end %>
      <% if CouchType.count == 0 %>
        <tr> <td colspan="3"> No se encontraron coincidencias </td> </tr>
      <% end %>
      <tr><td class="center-block" colspan="3"><%= link_to "Atrás", configurations_path, class: 'btn btn-info btn-sm' %></td></tr>

    </table>
    <div>
      <div>
        </body>

app/views/configurations/seleccionfechas.html.erb
<div class="container">
	<%= form_tag 'usuariosregistrados', method: :get do %>
		<h1 style="color:#6B8E23;" class="tipoRegistroCentro"> Seleccione las fechas </h1>
		
		<div class="field tipoRegistroCentro">
			<br />
			<%= label_tag :comienzo, "Fecha de inicio" %><br />
			<%= date_select :aux1, :comienzo, order: [:day, :month, :year], use_month_numbers: true, :start_year => Time.now.year - 2, :end_year => Time.now.year %>
		</div>	

		<div class="field tipoRegistroCentro">
			<br />	
			<%= label_tag :fin, "Fecha de fin" %><br />
			<%= date_select :aux2, :fin, order: [:day, :month, :year], use_month_numbers: true, :start_year => Time.now.year - 2, :end_year => Time.now.year %>
		</div>

		<div class="actions tipoRegistroCentro">
			<br />
			<%= submit_tag "Ver usuarios registrados", class: 'btn btn-default btn-sm' %>
			<%= submit_tag "Ver dinero recaudado", class: 'btn btn-default btn-sm' %>
			<br />
			<br />
			<%= link_to "Cancelar", :back, class: 'btn btn-default btn-sm' %>
	<% end %>
</div>

app/views/configurations/usuariosregistrados.html.erb
<body>
	<center>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1 style="color:#6B8E23;" class="text-center">Usuarios registrados</h1>
			<% if(@fin < @inicio) %>
				<div class="alert alert-warning">
					<h5 class="tipoRegistro" style="color:red"><strong> Ha ingresado un rango de fechas inválido. Por favor ingrese una fecha de fin mayor a la de inicio. </strong></h5>
				</div>
			<% else %>
				<% if(@inicio > Date.today) %>
					<div class="alert alert-warning">
						<h5 class="tipoRegistro" style="color:red"><strong> Ha ingresado un rango de fechas inválido. Por favor ingrese una fecha de inicio menor al dia de hoy.</strong></h5>
					</div>		
				<% else %>
					<% if (@premium) %>
						<% total = 0 %>
						<% usuariosPremium = User.all.where(esPremium: true) %>
						<% aux = usuariosPremium.where('"users"."fechaPremium" >= ? ', @inicio) %>
						<% todos = aux.where('"users"."fechaPremium" <= ?', @fin) %>
					<% else %>
						<% u = User.all.where("created_at >= ? ", @inicio) %>
						<% todos = u.where("created_at <= ?", @fin) %>
					<% end %>
					<% usuarios = todos.where(esAdmin: nil) %>
					<br />
					<table class = "table center">
						
						<tr>
							<th> Usuario </th>
							<th> Nombre de usuario </th>
							<th> Fecha de creacion </th>
							 <% if (@premium) %>
								<th> Abono </th>
							<% end %> 
						</tr>

						<% usuarios.each do |usuario| %>
							
							<tr>
								<td><p><%= usuario.nombre%>
									<%= usuario.apellido%></p>
								</td>

								<td> <%= usuario.nombreUsuario %> </td>
								<td> <%= usuario.created_at.day %>/<%= usuario.created_at.month %>/<%= usuario.created_at.year %> </td>
								<% if (@premium) %>
									<td> <%= usuario.precioPremium %> </td>
									<% total = total + usuario.precioPremium %>
								<% end %> 
							</tr>
						<% end %>

					</table>
					<% if (@premium) %>
						<h4><strong> Total recaudado: $ <%= total %></strong></h4>
					<% end %>
				<%end %>
			<% end %>
			<button class="btn btn-default btn-sm" type="button">
        		<%= link_to 'Atrás', :back, class: "btn-default" %>
      		</button> 
		</div>
	</div>
	</center>
</body>