config/routes.rb
Rails.application.routes.draw do

  get  'couch_types/index'
  get 'couches/index'
  resources :puntuacions
  resources :couches
  resources :configurations do
    get :seleccionfechas, on: :collection
    get :usuariosregistrados, on: :collection
  end
  resources :couch_types

  resources :reservas do
    get :aceptar, on: :member
    get :rechazar, on: :member
    get :cancelar, on: :member
    get :visto, on: :member
  end 
  resources :premiums
  resources :consultas

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions", :passwords => "passwords"}
  root 'couches#index'
  devise_scope :user do
    get '/users/show', to: 'registrations#show'
    get '/solicitudes', to:'registrations#missolicitudes'
    get '/misreservas', to: 'registrations#misreservas'
  end
  get '/couchinn', to: 'main#index'
  resources :premiums
  get '/puntuacion/recibidas', to: 'puntuacions#recibidas'
  get '/couch/reservas', to:'couches#indexreservas'
  get '/couch/estadias', to:'couches#indexestadias'

 
  

end

app/models/consulta.rb
class Consulta < ActiveRecord::Base
belongs_to :couch
belongs_to :user
default_scope -> { order('"consulta"."fechaPregunta"') }

def vista
	self.respuestaVista = true
	self.save
end
end

app/controllers/consultas_controller.rb
class ConsultasController < ApplicationController
before_action :get_consulta, only: [:edit, :update]

def get_consulta
	@consulta = Consulta.find(params[:id])
end

def new
	@consulta = Consulta.new
	@consulta.couch_id = params[:couch_id]
	@consulta.user_id = params[:user_id]
end

def create
	@consulta = Consulta.new(params.require(:consulta).permit(:pregunta, :couch_id, :user_id))
	@consulta.fechaPregunta = DateTime.now
	@consulta.userCouch = Couch.find(@consulta.couch_id).user.id
	@consulta.save
	redirect_to couch_path(@consulta.couch_id)
end

def edit
end

def update
	@consulta.update(params.require(:consulta).permit(:respuesta))
	@consulta.fechaRespuesta = DateTime.now
	@consulta.save
	redirect_to couch_path(@consulta.couch_id)
end

def index
	todasConsultas = Consulta.all
	consultasCouch = todasConsultas.where(userCouch: current_user.id)
	@consultasCouchSinRespuesta = consultasCouch.where(respuesta: nil)
	@consultasUsuario = todasConsultas.where(user_id: current_user.id)
	#@consultasSinRespuesta = @consultas.where(respuesta:nil)
	filtro = @consultasUsuario.where("respuesta != ?", "")
	@consultasConRespuesta = filtro.where(respuestaVista: false)
end

end

app/helpers/consultas_helper.rb
module ConsultasHelper
end

app/views/consultas/edit.html.erb
<div class="container">
	<h1 style="color:#6B8E23;" class="text-center"> Responder la consulta de <%= User.find(@consulta.user_id).nombreUsuario %> </h1>
	<br>
	<div class="row">	
		<div class="col-md-3 col-md-offset-4" >
			<h5><strong> Consulta </strong></h5>
			<p> <%= @consulta.pregunta %> </p>
		</div>
	</div>
	<%= form_for (@consulta), url: consulta_path, :method => :PATCH do |f| %>
		<div class="row">	
	  	<div class="col-md-3 col-md-offset-4" >
	      
	      <h5><%= f.label :respuesta, 'Respuesta'%></h5>
	  	  <%= f.text_area :respuesta, required: true, class: 'form-control', placeholder: 'Ingrese su respuesta', :cols => "15", :rows => "5"  %>

	  	</div>
	  </div>
		<br>
		<div class="row">
			<div class="col-md-3 col-md-offset-4">
				<%= f.submit "Responder", class: 'btn btn-success' %>
				<%= link_to "Cancelar", :back, class: 'btn btn-success' %>
			</div>
		</div>
	<% end %>
</div>

app/views/consultas/index.html.erb
<h1 style="color:#6B8E23;" class="text-center"> <strong> Consultas </strong></h1>
<div class="tipoRegistroCentro">
<% if (!@consultasConRespuesta.empty?) %>
	<em><small>Las consultas que le respondieron dejaran de aparecer una vez que ingrese al couch mediante el botón provisto.</small></em>
  <br />
  <br />
  <% @consultasConRespuesta.each do |consulta| %>
		<p> Le han respondido la consulta realizada en el couch de <strong><%= User.find(consulta.userCouch).nombre %> <%= User.find(consulta.userCouch).apellido %></strong> </p>
		<button class="btn btn-success btn-xs" type="button">
        <%= link_to 'Ver couch', couch_path(consulta.couch_id), class: "btn btn-success btn-xs" %>
    </button>
    <br />  
  <% end %>
<% end %>

<br />    
<% if (!@consultasCouchSinRespuesta.empty?) %>
    <em><small>Las consultas que realizaron sobre sus couches dejaran de aparecer una vez que las responda.</small></em>
    <br />
    <br />
   	<% @consultasCouchSinRespuesta.each do |c| %>
      <p> Usted tiene una consulta de <strong><%= User.find(c.user_id).nombre %> <%= User.find(c.user_id).apellido %></strong> en su couch <strong><%= Couch.find(c.couch_id).nombre %></strong> sin responder. </p>
   		<button class="btn btn-success btn-xs" type="button">
            <%= link_to 'Ver couch', couch_path(c.couch_id), class: "btn btn-success btn-xs" %>
      </button> 
      <br />
      <br />  
   	<% end %>
<% end %>
</div>

app/views/consultas/new.html.erb
<div class="container">
	<h1 style="color:#6B8E23;" class="text-center"> Realizar una consulta </h1>
	<br>
	<%= form_for (@consulta), url: consultas_path do |f| %>
		<div class="row">	
	  	<div class="col-md-3 col-md-offset-4" >
	      
	      <%= f.label :pregunta, 'Consulta'%>
	  	  <%= f.text_area :pregunta, required: true, class: 'form-control', placeholder: 'Ingrese su consulta', :cols => "15", :rows => "5"  %>

	  	  <%= f.hidden_field :couch_id%>
	  	  <%= f.hidden_field :user_id%>
	  	</div>
	  </div>
		<br>
		<div class="row">
			<div class="col-md-3 col-md-offset-4">
				<%= f.submit "Aceptar", class: 'btn btn-success' %>
				<%= link_to "Cancelar", :back, class: 'btn btn-success' %>
			</div>
		</div>
	<% end %>
</div>	