config/routes.rb
Rails.application.routes.draw do

  get  'couch_types/index'
  get 'couches/index'
  resources :puntuacions
  resources :couches
  resources :configurations do
    get :seleccionfechas, on: :collection
    get :usuariosregistrados, on: :collection
  end
  resources :couch_types

  resources :reservas do
    get :aceptar, on: :member
    get :rechazar, on: :member
    get :cancelar, on: :member
    get :visto, on: :member
  end 
  resources :premiums
  resources :consultas

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions", :passwords => "passwords"}
  root 'couches#index'
  devise_scope :user do
    get '/users/show', to: 'registrations#show'
    get '/solicitudes', to:'registrations#missolicitudes'
    get '/misreservas', to: 'registrations#misreservas'
  end
  get '/couchinn', to: 'main#index'
  resources :premiums
  get '/puntuacion/recibidas', to: 'puntuacions#recibidas'
  get '/couch/reservas', to:'couches#indexreservas'
  get '/couch/estadias', to:'couches#indexestadias'

 
  

end

app/views/layouts/_header.html.erb
<header>
  
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
   <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse"
            data-target=".navbar-ex1-collapse">
    </button>
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag "logo2.png", :alt => "logo", :title => "logo", :height => "140%" %>
     
    <% end %>
  </div> 
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <% cantidad = 0 %>
        <% if (!current_user.consultas.empty?) %>
          <% filtro = current_user.consultas.where("respuesta != ?", "") %>
          <% cantidad = filtro.where(respuestaVista: false).count %>
        <% end %>
        <% if(!current_user.couches.empty?) %>
          <% aux = Consulta.all.where(userCouch: current_user.id) %>
          <% cantidad = cantidad + aux.where(respuesta: nil).count %>
        <% end %>
        <% if cantidad != 0 %>
          <li><%= link_to 'Tiene consultas', consultas_path, :class => 'navbar-link' %></li>
          <li><span class="badge notificacion"><%= cantidad %></span></li>
        <% end %>
        
        <%reservas=0%>
        <% current_user.couches.all.each do |couch| %>
          <%reservas = reservas + couch.reservas.pendientes.count %>
        <%end%>

        <% suma=current_user.reservas.pendientes.count+reservas+current_user.reservas.confirmadas.novistas.count %>

        <li role="presentation" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reservas 
            <% if suma!= 0 %>
              <span class="badge"><%= suma %></span> 
            <% end %>
            <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to solicitudes_path do %>
                Reservas pendientes
                <% if current_user.reservas.pendientes.count != 0 %>
                  <span class="badge notificacion2"><%= current_user.reservas.pendientes.count %></span>
                <% end %>
                <% end %>
            </li>
            <li>
              <%= link_to solicitudes_path do %>
                Reservas Confirmadas
                <% if current_user.reservas.confirmadas.novistas.count != 0 %>
                  <span class="badge notificacion2"><%= current_user.reservas.confirmadas.novistas.count %></span>
                <% end %>
                <% end %>
            </li>
            <li role="separator" class="divider"></li>
            <li><%= link_to misreservas_path do %>
              Reservas sobre mis Couches
              <% if reservas != 0 %>
                <span class="badge notificacion2"><%= reservas %></span>
              <% end %>
              <% end %>
            </li>
          </ul>
        </li>
          

        <li> <%= link_to 'Nuevo Couch', new_couch_path, :class => 'navbar-link' %></li>
        <%if (current_user.esAdmin)%>
         <li> <%= link_to 'Configuración', configurations_path, :class => 'navbar-link' %></li4
        <%end%>
        <% if (current_user.esPremium == false) %>
          <li><%= link_to 'Ser premium!', premiums_path, :class => 'navbar-link' %></li>
        <% else %>
          <li><a href="#">Soy premium!</a></li>
        <% end %>
        <li><%=link_to users_show_path, class: 'navbar-brand' do %>
          <img src= <%= current_user.foto %> class = "img-circle" alt="imagen" style="width:30px;height:30px">
        <% end %>
        <li><%= link_to 'Cerrar sesión', destroy_user_session_path, :data => {:confirm => '¿Está seguro que quiere cerrar sesión?'} %></li>
      <% else %>
        <li><%= link_to "Registrarse", new_user_registration_path, :class => 'navbar-link'%></li>
        <li><%= link_to 'Iniciar sesión', new_user_session_path, :class => 'navbar-link' %></li>
      <% end %>
      </ul>
     </li>
    </ul>
  </div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CouchInn</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  
  <%= csrf_meta_tags %>
</head>
<!--<body class="bgimage"> -->
<body>
	 
	<!--<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p> -->
	<%= render 'layouts/header' %>
	<%= yield %>
		
</body>

</html>